# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculadora.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'calculadora.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61lculadora.proto\"4\n\x10OperacionRequest\x12\x0f\n\x07numero1\x18\x01 \x01(\x01\x12\x0f\n\x07numero2\x18\x02 \x01(\x01\"4\n\x0eOperacionReply\x12\x11\n\tresultado\x18\x01 \x01(\x01\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\"\x12\n\x10HistorialRequest\"%\n\x0eHistorialReply\x12\x13\n\x0b\x64\x65scripcion\x18\x01 \x01(\t\"\x1f\n\x0cLimpiarReply\x12\x0f\n\x07mensaje\x18\x01 \x01(\t2\xba\x02\n\x12\x43\x61lculadoraService\x12+\n\x05Sumar\x12\x11.OperacionRequest\x1a\x0f.OperacionReply\x12,\n\x06Restar\x12\x11.OperacionRequest\x1a\x0f.OperacionReply\x12\x31\n\x0bMultiplicar\x12\x11.OperacionRequest\x1a\x0f.OperacionReply\x12-\n\x07\x44ividir\x12\x11.OperacionRequest\x1a\x0f.OperacionReply\x12\x31\n\tHistorial\x12\x11.HistorialRequest\x1a\x0f.HistorialReply0\x01\x12\x34\n\x10LimpiarHistorial\x12\x11.HistorialRequest\x1a\r.LimpiarReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculadora_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERACIONREQUEST']._serialized_start=21
  _globals['_OPERACIONREQUEST']._serialized_end=73
  _globals['_OPERACIONREPLY']._serialized_start=75
  _globals['_OPERACIONREPLY']._serialized_end=127
  _globals['_HISTORIALREQUEST']._serialized_start=129
  _globals['_HISTORIALREQUEST']._serialized_end=147
  _globals['_HISTORIALREPLY']._serialized_start=149
  _globals['_HISTORIALREPLY']._serialized_end=186
  _globals['_LIMPIARREPLY']._serialized_start=188
  _globals['_LIMPIARREPLY']._serialized_end=219
  _globals['_CALCULADORASERVICE']._serialized_start=222
  _globals['_CALCULADORASERVICE']._serialized_end=536
# @@protoc_insertion_point(module_scope)
